apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-static
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 443 ssl;
        server_name web.k8s.local;

        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        # ✅ Fixed: Only allow TLSv1.3
        ssl_protocols TLSv1.3;

        location / {
          return 200 "Welcome to nginx-static!\n";
        }
      }
    }

