apiVersion: v1
kind: Namespace
metadata:
  name: cni-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
  namespace: cni-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80

