apiVersion: v1
kind: Namespace
metadata:
  name: relative-fawn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: relative-fawn
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init-db
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Initializing database...' && sleep 5"]
      - name: init-config
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Loading configuration...' && sleep 3"]
      containers:
      - name: wordpress
        image: wordpress:6.3
        env:
        - name: WORDPRESS_DB_HOST
          value: "localhost"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppass"
        ports:
        - containerPort: 80

