# Solution for Q10: WordPress Resource Requests Adjustment
#
# Node Resources:
#   CPU: 1 (1000m)
#   Memory: 2015360ki ≈ 1968 MiB
#
# Calculation:
#   Overhead (for node stability): 100m CPU, 200Mi memory
#   Available for pods: 900m CPU, 1768 MiB memory
#   Per pod (3 replicas): 300m CPU, ~589 MiB memory (603136ki)
#
# Step 1: Scale deployment to 0 replicas (helper tip)
# kubectl scale deployment wordpress -n relative-fawn --replicas=0
#
# Step 2: Patch the deployment to add resource requests
# kubectl patch deployment wordpress -n relative-fawn --type='json' \
#   -p='[
#     {"op": "add", "path": "/spec/template/spec/initContainers/0/resources", "value": {"requests": {"cpu": "300m", "memory": "589Mi"}}},
#     {"op": "add", "path": "/spec/template/spec/initContainers/1/resources", "value": {"requests": {"cpu": "300m", "memory": "589Mi"}}},
#     {"op": "add", "path": "/spec/template/spec/containers/0/resources/requests", "value": {"cpu": "300m", "memory": "589Mi"}}
#   ]'
#
# Step 3: Scale back to 3 replicas
# kubectl scale deployment wordpress -n relative-fawn --replicas=3
#
# Step 4: Verify
# kubectl get deployment wordpress -n relative-fawn
# kubectl get pods -n relative-fawn -l app=wordpress
# kubectl describe pod <pod-name> -n relative-fawn | grep -A 5 "Requests:"

---
# Complete deployment with resource requests (for reference)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: relative-fawn
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init-db
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Initializing database...' && sleep 5"]
        resources:
          requests:
            cpu: "300m"
            memory: "589Mi"
      - name: init-config
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Loading configuration...' && sleep 3"]
        resources:
          requests:
            cpu: "300m"
            memory: "589Mi"
      containers:
      - name: wordpress
        image: wordpress:6.3
        env:
        - name: WORDPRESS_DB_HOST
          value: "localhost"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppass"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "300m"
            memory: "589Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

