apiVersion: v1
kind: Namespace
metadata:
  name: synergy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy-deployment
  namespace: synergy
  labels:
    app: synergy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synergy
  template:
    metadata:
      labels:
        app: synergy
    spec:
      containers:
      - name: app
        image: nginx:1.25
        # Legacy application that writes logs to /var/log/synergy-deployment.log
        # We'll simulate this with a command that writes logs
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /var/log
            while true; do
              echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) [INFO] Legacy application log entry" >> /var/log/synergy-deployment.log
              sleep 5
            done
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        # Volume mount will be added as part of the solution
        # volumeMounts:
        # - name: log-volume
        #   mountPath: /var/log

